{
 "title": "Rubrik Status - Prometheus Data Source - New",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "objectName", "label": "Select a server  or object", "query": { "query": "rubrik_snappable_effective_sla" } },
   {
    "name": "selectedObjectSlaName",
    "query": {
     "query": "rubrik_snappable_effective_sla{objectName=\"$objectName\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Object Explorer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Object Protection Summary",
     "type": "table",
     "gridPos": { "h": 16, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "rubrik_snappable_effective_sla{objectName=\"$objectName\"}",
       "legendFormat": "{{objectType}} -> {{location}} -> {{objectName}}"
      }
     ]
    },
    {
     "title": "SLA Domain Information - $selectedObjectSlaName",
     "type": "table",
     "gridPos": { "h": 16, "w": 16, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "rubrik_sla_domain_summary{slaDomainName=\"$selectedObjectSlaName\"}",
       "legendFormat": "{{slaDomainName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rubrik Job Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Status Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
     "targets": [
      { "expr": "rubrik_node_status", "legendFormat": "{{nodeId}}" }
     ]
    },
    {
     "title": "24 Job Status",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rubrik_24h_succeeded_jobs", "legendFormat": "Succeeded" },
      { "expr": "rubrik_24h_cancelled_jobs", "legendFormat": "Cancelled" },
      { "expr": "rubrik_24h_failed_jobs", "legendFormat": "Failed" }
     ]
    },
    {
     "title": "Top 10 Nodes - Network Received Bytes",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(8,rubrik_node_network_received_bytes)",
       "legendFormat": "{{nodeId}}"
      }
     ]
    },
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 9, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rubrik_24h_succeeded_jobs" }
     ]
    },
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 11, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rubrik_24h_succeeded_jobs" }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 13, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "rubrik_24h_failed_jobs" }
     ]
    }
   ]
  },
  { "title": "Rubrik Storage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Used Storage Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rubrik_used_storage_bytes", "legendFormat": "Used Storage Bytes" }
   ]
  },
  {
   "title": "Available Snapshot Storage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "rubrik_available_storage_bytes", "legendFormat": "Available Snapshot Storage" }
   ]
  },
  {
   "title": "Relic Storage",
   "type": "timeseries",
   "description": "Relics are objects that were removed from the infrastructure (such as deleted VMs, DBS, etc.), but for which backup snapshots still exist in Rubrik CDM.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rubrik_relic_archive_storage_bytes)",
     "legendFormat": "Relic Archive Storage"
    },
    {
     "expr": "sum(rubrik_relic_local_storage_bytes)",
     "legendFormat": "Relic Local Storage"
    }
   ]
  },
  {
   "title": "Top 10 Relics (Local + Archive Combined)",
   "type": "stat",
   "description": "Relics are objects that were removed from the infrastructure (such as deleted VMs, DBS, etc.), but for which backup snapshots still exist in Rubrik CDM.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rubrik_relic_archive_storage_bytes + rubrik_relic_local_storage_bytes)"
    }
   ]
  },
  {
   "title": "vSphere VM Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rubrik_vsphere_vm_capacity_archive_used_bytes)",
     "legendFormat": "vSphere VM Archive Space Used"
    },
    {
     "expr": "sum(rubrik_vsphere_vm_capacity_local_used_bytes)",
     "legendFormat": "vSphere VM Local Space Used"
    }
   ]
  },
  {
   "title": "MSSQL Space Utilization - Rubrik CDM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rubrik_mssql_db_capacity_archive_used_bytes)",
     "legendFormat": "MSSQL Archive Space Used"
    },
    {
     "expr": "sum(rubrik_mssql_db_capacity_local_used_bytes)",
     "legendFormat": "MSSQL Local Space Used"
    }
   ]
  },
  {
   "title": "Top 10 vSphere VMs (Local + Archive Combined Storage)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rubrik_vsphere_vm_capacity_local_used_bytes + rubrik_vsphere_vm_capacity_archive_used_bytes)"
    }
   ]
  }
 ]
}